feat: introduce `all-flat` and `all-extend` config option
eslint-stylistic/eslint-stylistic pull request #165
Opened 2023-11-17 23:04 UTC by antfu

close #164

2023-11-17 23:52 UTC, Splines requested changes
Wow, you are really quick implementing the proposed feature, thanks a lot!

2023-11-17 23:52 UTC, Splines commented on docs/guide/config-presets.md
> +  // ...you other config items
`your` instead of `you`

2023-11-17 23:52 UTC, Splines commented on docs/guide/config-presets.md
> +  // ...you other config items
`your` instead of `you`

2023-11-18 10:37 UTC, closed without merging

2023-11-18 10:37 UTC, antfu commented
Close in favor of #168, so that we can release it before introducing #144